male(harry).
male(dudley).
male(vernon).
male(james).
male(paul).
male(albert).
female(ruth).
female(helen).
female(petunia).
female(lili).
male(bob).
female(bertha).
female(brenda).
parent_of(bob,paul).
parent_of(brenda,paul).
parent_of(bob,bertha).
parent_of(brenda,bertha).
parent_of(paul,petunia).
parent_of(paul,lili).
parent_of(helen,lili).
parent_of(helen,petunia).
parent_of(petunia,dudley).
parent_of(vernon,dudley).
parent_of(lili,harry).
parent_of(james,harry).
parent_of(albert,james).
parent_of(ruth,james).
father_of(Father,Child):-
	parent_of(Father,Child),
	male(Father).
mother_of(Mother,Child):-
	parent_of(Mother,Child),
	female(Mother).
grandfather_of(Grandfather,Child):-
	father_of(Grandfather,Z),
	parent_of(Z,Child).
grandmother_of(Grandmother,Child):-
	mother_of(Grandmother,Z),
	parent_of(Z,Child).
sister_of(Sister,Person):-
	female(Sister),
	parent_of(X,Sister),
	parent_of(X,Person).
brother_of(Brother,Person):-
	male(Brother),
	parent_of(X,Brother),
	parent_of(X,Person).
aunt_of(Aunt,Person):-
	sister_of(Aunt,X),
	parent_of(X,Person).
uncle_of(Uncle,Person):-
	brother_of(Uncle,X),
	parent_of(X,Person).
ancestor_of(X,Y):-
	parent_of(X,Y).
ancestor_of(X,Y):-
	parent_of(X,Z),
	ancestor_of(Z,Y).
